### PR TITLE
Skeleton

### PR DESCRIPTION
**Pull request by eugent482**
Hello dear Tech leads. Please check this skeleton and make a decision about what to do next.

### CODE REVIEW

**Review by TREN-D — APPROVED** [review]
All is fine!

**Review by TREN-D — APPROVED** [review]
All is fine v2.0!

**Comment by andriipetryna** [comment]
@eugent482
Why there are 2 .gitignore files (.gitignore and InternetHospital.WebApp/.gitignore)? Is second file necessary?

**Comment by eugent482** [comment]
Both .gitignore files was created by visual studio. They have some differences, so I haven't been changing them.

**Comment by katemalash** [comment]
> @eugent482
> Why there are 2 .gitignore files (.gitignore and InternetHospital.WebApp/.gitignore)? Is second file necessary?

It should be single .gitignore !!!

**Comment by eugent482** [comment]
Now it's single one.

**Review by andriipetryna — COMMENTED** [review]
Remove SampleDataController and default examples of Angular components

**Review by andriipetryna — APPROVED** [review]

**Review by serhiidotsyk — APPROVED** [review]

**Review by andriipetryna — COMMENTED** [review]
Remove default ValuesController

**Review by andriipetryna — APPROVED** [review]
All is okay, you may merge it. I think it's better to use merging with squashing.

**Pull request merged**
